// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_tsgarch_TMBExports
#include <TMB.hpp>
#include "distfun.h"
#include "garchextra.h"
#include "egarchkappa.h"
#include "aparchkappa.h"
#include "fgarchkappa.h"
#include "gjrkappa.h"
#include "garchfun.hpp"
#include "egarchfun.hpp"
#include "aparchfun.hpp"
#include "cgarchfun.hpp"
#include "fgarchfun.hpp"
#include "aparchjac.hpp"
#include "fgarchjac.hpp"
#include "gjrgarchfun.hpp"
#include "gjrgarchjac.hpp"
#ifndef M_PI
#define M_PI 3.141592653589793116
#endif

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "garch") {
      return garchfun(this);
  } else if(model == "egarch"){
      return egarchfun(this);
  } else if(model == "aparch"){
      return aparchfun(this);
  } else if(model == "gjrgarch"){
      return gjrgarchfun(this);
  } else if(model == "fgarch"){
      return fgarchfun(this);
  } else if(model == "cgarch"){
      return cgarchfun(this);
  } else if(model == "gjrgarchjacobian"){
      return gjrgarchjac(this);
  } else if(model == "aparchjacobian"){
      return aparchjac(this);
  } else if(model == "fgarchjacobian"){
      return fgarchjac(this);
  } else {
    error("Unknown model.");
  }
  return 0;
}
