# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.garchfilter <- function(residuals, v, initstate, omega, alpha, beta, model) {
    .Call(`_tsgarch_garchfilter`, residuals, v, initstate, omega, alpha, beta, model)
}

.egarchfilter <- function(residuals, v, initstate, omega, alpha, gamma, beta, kappa, model) {
    .Call(`_tsgarch_egarchfilter`, residuals, v, initstate, omega, alpha, gamma, beta, kappa, model)
}

.aparchfilter <- function(residuals, v, initstate, omega, alpha, gamma, beta, delta, model) {
    .Call(`_tsgarch_aparchfilter`, residuals, v, initstate, omega, alpha, gamma, beta, delta, model)
}

.gjrgarchfilter <- function(residuals, negative_indicator, v, initstate, omega, alpha, gamma, beta, model) {
    .Call(`_tsgarch_gjrgarchfilter`, residuals, negative_indicator, v, initstate, omega, alpha, gamma, beta, model)
}

.fgarchfilter <- function(residuals, v, initstate, omega, alpha, gamma, eta, beta, delta, model) {
    .Call(`_tsgarch_fgarchfilter`, residuals, v, initstate, omega, alpha, gamma, eta, beta, delta, model)
}

.cgarchfilter <- function(residuals, v, initstate, omega, alpha, rho, phi, beta, model) {
    .Call(`_tsgarch_cgarchfilter`, residuals, v, initstate, omega, alpha, rho, phi, beta, model)
}

